// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-search-index.js
// Last updated: 2025-11-09T00:22:11.835Z

import Fuse from 'fuse.js'
import type { SearchableContent, SearchResult, SearchOptions } from '../types/search'

/**
 * Search content index - automatically generated from page metadata
 * To update: run `yarn generate-search-index` or `node scripts/generate-search-index.js`
 */
const searchContent: SearchableContent[] = [
  {
    id: 'glossary',
    title: 'Glossary',
    content: 'Comprehensive glossary of neuroscience and mathematical terms used throughout the nREM platform. Currently under development, this resource will include neuroscience terminology, mathematical concepts and formulas, statistical methods, and research techniques. Browse by category including neuroscience terms, mathematical concepts, statistical methods, and research techniques. The glossary will feature interactive cross-references and visual examples to help clarify complex terminology.',
    excerpt: 'Comprehensive reference for neuroscience and mathematical terminology (coming soon)',
    path: '/glossary',
    tags: ['glossary', 'definitions', 'terminology', 'reference', 'dictionary', 'neuroscience-terms', 'mathematics'],
    category: 'Reference',
    type: 'page',
    metadata: {
    chapter: 'Reference',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'platform-guide',
    title: 'Platform Guide',
    content: 'Welcome to nREM (neuroscience Research Explained Modestly) - where complex neuroscience is simplified through immersive 3D visualizations. Learn how to interact with scroll-activated 3D models embedded in articles, use the expand icon (「｣) to explore models in detail, view footnotes for additional research context, and navigate the platform. This guide demonstrates interactive features using a neuron model with voltage animations and bloom effects. Discover how nREM transforms neuroscience education through observation and visualization.',
    excerpt: 'Interactive guide to using nREM\\\'s 3D visualization platform for neuroscience education',
    path: '/platform-guide',
    tags: ['guide', 'navigation', 'help', 'tutorial', 'how-to', '3d-models', 'platform', 'nrem'],
    category: 'Help',
    type: 'page',
    metadata: {
    chapter: 'Help',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'visual-receptors-retinal-interaction',
    title: 'Visual receptors and retinal interaction',
    content: 'Explore H. K. Hartline\\\'s Nobel Prize-winning research on visual processing using Limulus polyphemus (horseshoe crab) as a model organism. This article covers the experimental setup for studying single optic nerve fibers, the discovery of sensory adaptation in visual receptors, and the groundbreaking concept of lateral inhibition in the retina. Learn how Hartline\\\'s work demonstrated that the basic mechanism of the receptor emphasizes change rather than steady state.',
    excerpt: 'Hartline\\\'s Nobel Prize research on lateral inhibition and visual receptors using horseshoe crab ommatidia',
    path: '/topic1',
    tags: ['model-organisms', 'vision', 'retina', 'lateral-inhibition', 'hartline', 'limulus', 'ommatidia', 'sensory-adaptation'],
    category: 'Senses',
    type: 'page',
    metadata: {
    chapter: 'Chapter 1',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'ommatidia-lateral-inhibition-simulation',
    title: 'Lateral Inhibition Simulation',
    content: 'Interactive 3D NEURON simulation demonstrating lateral inhibition between two neighboring eccentric cells from horseshoe crab ommatidia. Watch voltage changes in real-time as coupled neurons respond to light stimulation. Toggle between two-cell and single-cell views to compare inhibitory interactions. Features playback controls with adjustable animation speed (0.25x to 2x) to explore the 200ms simulation in detail. This visualization brings Hartline\\\'s lateral inhibition concept to life with computational neuroscience.',
    excerpt: 'Interactive NEURON simulation of lateral inhibition in horseshoe crab eccentric cells with real-time voltage visualization',
    path: '/topic2',
    tags: ['neuroscience', 'lateral-inhibition', 'ommatidia', 'horseshoe-crab', 'NEURON', 'simulation', 'voltage', 'eccentric-cells', 'computational-neuroscience', '3d-visualization'],
    category: 'Computational Neuroscience',
    type: 'page',
    metadata: {
    chapter: 'Chapter 2',
    difficulty: 'intermediate',
    estimatedReadTime: 5
  }
  }
]

// Fuse.js configuration for fuzzy search
const fuseOptions = {
  keys: [
    { name: 'title', weight: 0.4 },
    { name: 'content', weight: 0.3 },
    { name: 'tags', weight: 0.2 },
    { name: 'category', weight: 0.1 }
  ],
  threshold: 0.4,
  includeScore: true,
  minMatchCharLength: 3,
  ignoreLocation: true
}

// Create Fuse instance
const fuse = new Fuse(searchContent, fuseOptions)

/**
 * Perform a search query with options
 * @param options - Search options including query, filters, and limits
 */
export function performSearch(options: SearchOptions): SearchResult[] {
  const { query, tags, category, type, maxResults = 10 } = options

  if (!query || query.length < 3) {
    return []
  }

  // Perform fuzzy search
  let results = fuse.search(query, { limit: maxResults * 2 })

  // Apply additional filters
  if (tags && tags.length > 0) {
    results = results.filter(result =>
      tags.some(tag => result.item.tags.includes(tag))
    )
  }

  if (category) {
    results = results.filter(result => result.item.category === category)
  }

  if (type) {
    results = results.filter(result => result.item.type === type)
  }

  // Transform to SearchResult format and limit
  return results.slice(0, maxResults).map(result => ({
    item: result.item,
    score: result.score || 0,
    matches: result.matches as any
  }))
}

/**
 * Get search suggestions based on partial query
 * @param partialQuery - Partial search string
 * @param limit - Maximum number of suggestions (default: 5)
 */
export function getSearchSuggestions(partialQuery: string, limit: number = 5): string[] {
  if (!partialQuery || partialQuery.length < 1) {
    return []
  }

  const query = partialQuery.toLowerCase()
  const suggestions = new Set<string>()

  // Suggest from titles
  searchContent.forEach(item => {
    if (item.title.toLowerCase().includes(query)) {
      suggestions.add(item.title)
    }
  })

  // Suggest from tags
  searchContent.forEach(item => {
    item.tags.forEach(tag => {
      if (tag.toLowerCase().includes(query)) {
        suggestions.add(tag)
      }
    })
  })

  return Array.from(suggestions).slice(0, limit)
}

/**
 * Debounce utility function
 * @param func - Function to debounce
 * @param wait - Wait time in milliseconds
 */
export function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait: number
): (...args: Parameters<T>) => void {
  let timeout: ReturnType<typeof setTimeout> | null = null

  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      timeout = null
      func(...args)
    }

    if (timeout) {
      clearTimeout(timeout)
    }
    timeout = setTimeout(later, wait)
  }
}

/**
 * Get all searchable content
 */
export function getAllContent(): SearchableContent[] {
  return searchContent
}

/**
 * Get content by category
 */
export function getContentByCategory(category: string): SearchableContent[] {
  return searchContent.filter(item => item.category === category)
}

/**
 * Get content by tag
 */
export function getContentByTag(tag: string): SearchableContent[] {
  return searchContent.filter(item => item.tags.includes(tag))
}

/**
 * Get all unique categories
 */
export function getAllCategories(): string[] {
  return Array.from(new Set(searchContent.map(item => item.category)))
}

/**
 * Get all unique tags
 */
export function getAllTags(): string[] {
  const tags = new Set<string>()
  searchContent.forEach(item => {
    item.tags.forEach(tag => tags.add(tag))
  })
  return Array.from(tags).sort()
}
