// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-search-index.js
// Last updated: 2025-11-08T23:01:15.010Z

import Fuse from 'fuse.js'
import type { SearchableContent, SearchResult, SearchOptions } from '../types/search'

/**
 * Search content index - automatically generated from page metadata
 * To update: run `yarn generate-search-index` or `node scripts/generate-search-index.js`
 */
const searchContent: SearchableContent[] = [
  {
    id: 'glossary',
    title: 'Glossary',
    content: 'Comprehensive glossary of neuroscience and mathematical terms used throughout the platform. Find definitions, explanations, and related concepts for key terminology.',
    excerpt: 'Definitions and explanations of key neuroscience and mathematical terms.',
    path: '/glossary',
    tags: ['glossary', 'definitions', 'terminology', 'reference'],
    category: 'Reference',
    type: 'page',
    metadata: {
    chapter: 'Reference',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'platform-guide',
    title: 'Platform Guide',
    content: 'Learn how to navigate and make the most of this neuroscience learning platform. This guide covers getting started, navigation, search features, and platform overview.',
    excerpt: 'Complete guide to using the neuroscience learning platform effectively.',
    path: '/platform-guide',
    tags: ['guide', 'navigation', 'help', 'tutorial'],
    category: 'Help',
    type: 'page',
    metadata: {
    chapter: 'Help',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'topic1-page1',
    title: 'Visual receptors and retinal interaction',
    content: 'The Nobel Prize in Physiology or Medicine in 1967 was awarded jointly to Haldan Keffer Hartline, Ragnar Granit, and George Wald for their discoveries concerning visual processes. In his Nobel Lecture, Hartline explains his work on the concept of lateral inhibition, a defining characteristic of retinal interactions that demonstrates the importance of contrast in visual processing.',
    excerpt: 'the basic mechanism of the receptor is one that emphasizes change.',
    path: '/topic1/page1',
    tags: ['model organisms', 'vision', 'retina', 'lateral-inhibition'],
    category: 'Senses',
    type: 'page',
    metadata: {
    chapter: 'Chapter 1',
    difficulty: 'beginner',
    estimatedReadTime: 5
  }
  },
  {
    id: 'topic2-page1',
    title: 'Two Ommatidia Lateral Inhibition Simulation',
    content: 'Interactive 3D visualization of two neighboring ommatidia (eccentric cells) from the horseshoe crab compound eye, demonstrating lateral inhibition with NEURON simulation data.',
    excerpt: 'Visualizing lateral inhibition in horseshoe crab ommatidia with live voltage data.',
    path: '/topic2/page1',
    tags: ['neuroscience', 'lateral-inhibition', 'ommatidia', 'horseshoe-crab', 'NEURON', 'simulation', 'voltage'],
    category: 'Neuroscience',
    type: 'page',
    metadata: {
    chapter: 'Chapter 2',
    difficulty: 'intermediate',
    estimatedReadTime: 5
  }
  }
]

// Fuse.js configuration for fuzzy search
const fuseOptions = {
  keys: [
    { name: 'title', weight: 0.4 },
    { name: 'content', weight: 0.3 },
    { name: 'tags', weight: 0.2 },
    { name: 'category', weight: 0.1 }
  ],
  threshold: 0.4,
  includeScore: true,
  minMatchCharLength: 3,
  ignoreLocation: true
}

// Create Fuse instance
const fuse = new Fuse(searchContent, fuseOptions)

/**
 * Perform a search query with options
 * @param options - Search options including query, filters, and limits
 */
export function performSearch(options: SearchOptions): SearchResult[] {
  const { query, tags, category, type, maxResults = 10 } = options

  if (!query || query.length < 3) {
    return []
  }

  // Perform fuzzy search
  let results = fuse.search(query, { limit: maxResults * 2 })

  // Apply additional filters
  if (tags && tags.length > 0) {
    results = results.filter(result =>
      tags.some(tag => result.item.tags.includes(tag))
    )
  }

  if (category) {
    results = results.filter(result => result.item.category === category)
  }

  if (type) {
    results = results.filter(result => result.item.type === type)
  }

  // Transform to SearchResult format and limit
  return results.slice(0, maxResults).map(result => ({
    item: result.item,
    score: result.score || 0,
    matches: result.matches as any
  }))
}

/**
 * Get search suggestions based on partial query
 * @param partialQuery - Partial search string
 * @param limit - Maximum number of suggestions (default: 5)
 */
export function getSearchSuggestions(partialQuery: string, limit: number = 5): string[] {
  if (!partialQuery || partialQuery.length < 1) {
    return []
  }

  const query = partialQuery.toLowerCase()
  const suggestions = new Set<string>()

  // Suggest from titles
  searchContent.forEach(item => {
    if (item.title.toLowerCase().includes(query)) {
      suggestions.add(item.title)
    }
  })

  // Suggest from tags
  searchContent.forEach(item => {
    item.tags.forEach(tag => {
      if (tag.toLowerCase().includes(query)) {
        suggestions.add(tag)
      }
    })
  })

  return Array.from(suggestions).slice(0, limit)
}

/**
 * Debounce utility function
 * @param func - Function to debounce
 * @param wait - Wait time in milliseconds
 */
export function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait: number
): (...args: Parameters<T>) => void {
  let timeout: ReturnType<typeof setTimeout> | null = null

  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      timeout = null
      func(...args)
    }

    if (timeout) {
      clearTimeout(timeout)
    }
    timeout = setTimeout(later, wait)
  }
}

/**
 * Get all searchable content
 */
export function getAllContent(): SearchableContent[] {
  return searchContent
}

/**
 * Get content by category
 */
export function getContentByCategory(category: string): SearchableContent[] {
  return searchContent.filter(item => item.category === category)
}

/**
 * Get content by tag
 */
export function getContentByTag(tag: string): SearchableContent[] {
  return searchContent.filter(item => item.tags.includes(tag))
}

/**
 * Get all unique categories
 */
export function getAllCategories(): string[] {
  return Array.from(new Set(searchContent.map(item => item.category)))
}

/**
 * Get all unique tags
 */
export function getAllTags(): string[] {
  const tags = new Set<string>()
  searchContent.forEach(item => {
    item.tags.forEach(tag => tags.add(tag))
  })
  return Array.from(tags).sort()
}
